[mypy]
python_version = 3.10
strict = True
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True
warn_unreachable = True

# Ignore missing imports for third-party libraries without stubs
[mypy-tests.*]
strict = False
disallow_untyped_defs = False

[mypy-kafka.*]
ignore_missing_imports = True

[mypy-py2neo.*]
ignore_missing_imports = True

[mypy-networkx.*]
ignore_missing_imports = True

[mypy-pyod.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True
